# This script takes multiple exon coverage files generated by command:
# samtools bedcov <BED> <BAM> | perl -F"\t" -ane 'chomp @F; print join("\t", @F,sprintf("%.3f", $F[-1]/($F[2]-$F[1]))),"\n"' > <NAME>_exonCov.bed
# it cumulatively adds the coverage of file1+file2, file1+file2+file3 and so on and generate the new cumulative exonCoverage files


args = commandArgs(trailingOnly=TRUE)

covFiles <- args
# covFiles <- list.files(path = "E:/Chris_UM/Analysis/CoreData/13_exonCovAnalysis/TA1_exonCoverage", pattern = "*exonCov.bed", full.names = T)

# read the first file and store its table
t1 <- read.table(covFiles[1], header = FALSE)
write.table(t1, file="exonCov_1.bed", sep = "\t", col.names = FALSE, row.names = FALSE, quote = FALSE)

comb <- 1

for(i in 2:length(covFiles)){
  print(covFiles[i])
  # read the next file as table
  tempTab <- read.table(file = covFiles[i], header = F)
  
  # calculate the new cumulative read count for each exon region by adding the counts in two tables
  t1$V4 <- t1$V4 + tempTab$V4
  # calculate the mean coverage
  t1$V5 <- round(t1$V4/(t1$V3 - t1$V2), 3)
  
  #new file name
  comb <- paste(comb,i,sep = "")
  outFile <- paste("exonCov_",comb,".bed", sep = "")
  
  #write the cumulative coverage data to the new file
  write.table(t1, file = outFile, sep = "\t", col.names = F, row.names = F, quote = F)
  
}



