


#' Remove redundent GO genesets from gseGO result
#' 
#' This function removes the redundent GO genesets from gseGO results.
#' It uses GOSemSim::mclusterSim to find the distance between the genesets.
#' Then this distance matrix is used for clustering and the resulting
#' cluster is cut at appropriate height to assign the similar genesets to
#' single group. The gseaResult object is then modified to select only one
#' representative from each clustercut. If a cluster has both up and down
#' regulated genesets, all the genesets are selected from this cluster.
#'
#' @param obj gseaResult object
#' @param orgGo GOSemSimDATA object generated by function GOSemSim::godata()
#'
#' @return modified gseaResult object
#' @export
#'
#' @examples NA
simplify_gsea <- function(obj, orgGo){
  
  ## remove redundent GO genesets from GSEA result
  ## do not use the GO term IDs for doing GO geneset similarity calculation.
  ## it does not give consistent results: GO genesets with opposite NSEs are combined
  ## therefore use the gene list for each GO genesets
  geneSets <- sapply(X = structure(obj$core_enrichment, names = obj$ID),
                     FUN = function(x){
                       genes = strsplit(x, split = "/", fixed = T)
                     }
  )
  
  ## get the genesets for the current result GO term sets
  geneSets <- obj@geneSets[obj$ID]
  
  cat("Generating GO geneset similarity estimates\n")
  
  ## generate similarity matrix based on genesets
  gsSim <- GOSemSim::mclusterSim(clusters = geneSets, semData = orgGo, measure = "Wang")
  
  cat("Clustering similar GO genesets and selecting representative genesets\n")
  
  ## cluster the IDs
  hc <- hclust(as.dist(1 - gsSim), method = "average") %>% as.dendrogram()
  
  # hc %>% sort() %>% plot()
  
  ## cut the cluster to assign closer IDs to one group
  dd <- hc %>% dendextend::cutree(h = 0.1)
  
  gseaClust <- data.frame(id = names(dd), clust = dd, stringsAsFactors = F)
  
  ## modify the result to remove closely related GO genesets
  backupRes <- obj@result
  
  newRes <- obj@result %>% 
    dplyr::left_join(y = gseaClust, by = c("ID" = "id")) %>% 
    dplyr::group_by(clust) %>% 
    dplyr::arrange(desc(setSize), .by_group = TRUE) %>% 
    dplyr::mutate(rowId = row_number(),
                  conflict = if_else(condition = (all(NES < 0) | all(NES > 0)),
                                     true = "No", false = "Yes")) %>% 
    dplyr::ungroup() %>% 
    dplyr::filter((rowId == 1 & conflict == "No") | conflict == "Yes") %>% 
    dplyr::select(-clust, -rowId, -conflict) %>% 
    as.data.frame()
  
  ## remember to set the rownames
  rownames(newRes) <- newRes$ID
  
  obj@result <- newRes
  
  cat("Done...\n")
  
  return(obj)

}


###########################################################################

















