#!/usr/bin/perl -w

use strict;
use warnings;

my $usage = 'This script parse the genome file and finds the given motif sequence coordinates in the complete genome. It returns each position as BED format
USAGE: perl findMotifPosInGenome.pl <GENOME FILE in FASTA format>
';

if($#ARGV == -1){
	print STDERR "Please provide genome file\n";
	print STDERR $usage;
	die;
}

my $motif = 'CCAAT|ATTGG';


open(my $fh, $ARGV[0]) or die "Cannot open file $ARGV[0]: $!\n";

my ($chr, $pos, $lastLine, $lastLineLength) = ('', 0, '', 0);

my $firstSeqLine = 0;
my $count = 0;

while(my $line = <$fh>){
	chomp $line;
	
	if($line =~ m/^>(\S+)/){
		$chr = $1;
		$pos = 0;
		$firstSeqLine = 1;
	}
	else{
		if($firstSeqLine){
			$lastLine = $line;
			$lastLineLength = length $lastLine;
			
			$firstSeqLine = 0;
		}
		else{
			my $thisLine = $lastLine.$line;
			
			while($thisLine=~m/($motif)/g){
				$count++;
				my $position = pos($thisLine);
				
				my $start = $pos + $position - 4;
				print join("\t", $chr, $start, $start+4, $count.'_'.$1),"\n";
			}
			
			$pos += length($thisLine)-4;
			
			$lastLine = substr($line, length($line) - 4);
			$lastLineLength = length $lastLine;
		}
	}
}

#Process the last line
#Not needed



close($fh);



__DATA__
>1 dna:chromosome chromosome:GRCz10:1:1:58871917:1 REF
GATCTTAAACATTTACCAATCCTGCAAACATTTTCAATCATTACATTGTCATTTCCCCTC
CAAATTAAATTTAGCCAGAGGCGCACAACATACGACCTCTAAAAAAGGTGCTGTAACATG
TACCTATATGCAGCACCACTATATGAGAGCGGCATAGCAGTGTTTAGTCACTTGGTTGCT
TTGTTTATATTAACTTGAAAGTGTGTTTTAGCTATTGAGTTTAAACAAAGGGAGCGGTTT
ACATTGAATTAAAGGCAACTACTGATGCCAATTGTAATGTTTCAAAGAGCTGTTGCAGCA
TGAGTGGAAAATAAAACCGTATTAGTGCTGCCTGGCCCAGTTTGGCACAAAATGGAGCGA
TTCCATTAAGAGAACGATTCAGCATAAGTGGAACAGCTAAAGTTTATGAAAATTTTTAAT
CTGGATGTAGAGAATCTCATAACACAGAAACAGCACTCCTAAAGATGCATTTATACTTCT
GCATAGAGCACACAAGTATGCTTCAGCACAACCTGTGCATGGTCACATACCAATTGCTGT
>2 dna:chromosome chromosome:GRCz10:1:1:58871917:1 REF
GGCAGTCAGACAATGATGCACACCTCAATGAATAGAGCAAGCTGTGATTGGTCAGCTTTG
TAGAGCTGACGTGTGCCCTAACCTAGTCCTCATCTTCAGTCAGTAATTTGGGGGCCATGT
CTGACAGCAACCTGTGTAAGGCCAGATGAAGCATCTGTAAAACTCAATTTCTTCATCGTA
ATGTTGCCAAAATGACGAGCTCCAATTAACTGATGCAGAAAAGCTTATTCATGCTTTCAT
TACCTCTCGGTTAGACTACTGTAATGAGTTACTAGGCGGATGCCCTGCCGGCCTCACTAA
CAAACTGCAGCTGGTTCAAAATGCAGCTGCTGGAGTGCTTTCTAGAACTAAGAAATCACA
GTACTCTAGTTCTTTCATCGGTGCATTGACTCCCATTAAATATTTAATTTACAATGTTAG
TGTTTAAGTACAAAACCCTCAATGCTTTAGCTGCCAATTATTTGAGGGAGCTCCTGGTGT
ATTATAGAGCATGAGATTGATTCTTTTAAGACCCTAAAGTGACCCACGAGTCTACATATT
GATCCTGAAGGGTCAGTCTGTACACCAGCCGGTGACCTCTCATCTACAGCTTCTCCACAA
TGGATGTCCACCATTCTCCAGTCTCCGGTGCCTAGACTGCAGCTCTGTACAGTAAGTCTG
GCCAGAGGAGAAATGGTCATGCCCAACTGAGCCTGGTTTGGAGGTTATTTTTCCCCTTTA
>3 dna:chromosome chromosome:GRCz10:1:1:58871917:1 REF
TCTTACACCTTAACCTTACCAATAGTAAATTCTGAGGTAACAAGTCTTCAGTAGATCTCA
TGTTTGAATTGATTATTTTTTGAAAATTTCTTTAATGACTGGTGTAGGTGGTGTTGATGC
ACAATGTGCTGTTGTGTGGAGGTGCTAATCACCAGTAGAAGACTGGGCTTCATTTAAGGC
CTGTTCGCCCCCGGCCACCTTCCCTGCGTGCTGTCCAAGTGGACCCAGGGAGGCTGAATA
CTTACCACTCCCCAATGTGACCTTTTGTTAACACCGCAAGGTTGCCCAGGTCACCCGAGA
AGAGTCTGAAGATGTCTCTCTATGGGGCCTACTCTGGCTAATCCAGAGACCAGGCTCCCC
AGGACCCCAGATATCTCCAAGGAACAGGAGAGCCCTTGCCCAAATCAGCTGAATCTAACA
GGTAGATTCAGGAGTAAAAGTCGGCAATGAACTGGTCACTGCCTACTCACTCCCTGCTGA
TTTTCTCCAGAATACTTCCAGTCAACATTCAAGGACTTCCATAAATCCAAGATGACCAAA
GAACTCACACAAATGTGATAAGAAGCATTCAAAGAGATAATCCTGACCTTAATTACCCAA
TTAGAAGTGAAAAATTTAAGAGGCCAGGTCGAGGTTCAGTCTGGCGGATATATCTCTGTA
GATATATCATTCTTCTACCAGATGTCTCCCCTAAGGCAATGCAAGAACCAAGCAGACATC
ATCCTTATCAGGGATAACCGTTGGGAGCATTACCCTGAAGACCAATACACCCTTGGCCGT
TGACCAGGTTTTGAGACACAGCATTTCGGCAATGGTGATGACCATTTGTTTGTTTGTATT
TTTCTTTGTTCTTGTTTGTATATTTTTATTCAGAATTTGATTATCTGATGTCTAAGTTGT
TTTCCCATACTTTGATTATCATATTTAAGCTTATGAACCAATTTAAAATCGTGTTTTATT
AGAGAATAGACCATATGCAAATGACTCATTAGTATTCGTGTTTTTGGACCAATCCTGTGT
CCAATGTCCTGAGTGTGCTTTCGGTCAGGTTTAATCCTTTATATCTCGGCCGTTTTTTCA




