library(chipmine)
library(org.Anidulans.eg.db)



rm(list = ls())


path = "E:/Chris_UM/Analysis/23_Shuhui_SM_OE_project/old/samples/chris_mix43_h3k27ac/"
setwd(path)


## genes to read
file_genes = "E:/Chris_UM/Database/A_Nidulans/AN_genesForPolII.bed"
file_geneInfo <- "E:/Chris_UM/Database/A_Nidulans/A_nidulans_FGSC_A4_geneClasses.txt"


outpath = path

## this file should have columns: sampleId, IP_tag, profileName, matFile, polIIExpFile, clusterFile, TF
file_sampleInfo <- "expt_info.txt"

## remember to change the argument "matSource" if the matrix is generated by Miao's script
# "deeptools", "miao", "normalizedmatrix", "normalizedmatrix_5kb"
matrixType <- "miao"
matrixDim = c(40, 40, 40, 10)

showExpressionHeatmap = FALSE

##################################################################################
## read experiment information
exptData <- readr::read_tsv(file = file_sampleInfo, na = "NA")


## genes to read
geneSet <- data.table::fread(file = file_genes, header = F,
                             col.names = c("chr", "start", "end", "gene", "score", "strand")) %>% 
  dplyr::mutate(length = end - start)


## read the cluster information for the first sample
clusterData <- data.table::fread(file = exptData$clusterFile[1], sep = "\t", header = T, stringsAsFactors = F) %>% 
  dplyr::left_join(y = geneSet, by = c("gene" = "gene"))

## gene information annotations: cluster and TF and polII expression values
geneInfo <- add_gene_info(file = file_geneInfo, clusterDf = clusterData)

head(geneInfo)

polII_ids <- exptData$sampleId[which(exptData$IP_tag == "polII")]
# polII_expIds <- paste("is_expressed.", polII_ids, sep = "")
tfIds <- exptData$sampleId[which(exptData$IP_tag %in% c("HA", "MYC", "TAP") & exptData$TF != "untagged")]


anLables <- list()
anLables[["is_SM_gene"]] = "SM gene"
anLables[["is_TF"]] = "Transcription Factor"
anLables[["gene_length"]] = "Gene Length"

##################################################################################
## optionally calculate a mean profile matrix and generate a color based on this
matList <- profile_matrix_list(exptInfo = exptData, geneList = geneInfo$gene,
                               source = matrixType,
                               up = matrixDim[1], target = matrixDim[2], down = matrixDim[3])

meanMatrix <- getSignalsFromList(lt = matList)
quantile(meanMatrix, c(seq(0, 0.9, by = 0.1), 0.95, 0.99, 0.992, 0.995, 0.999, 0.9999, 1), na.rm = T)
meanColor <- colorRamp2(quantile(meanMatrix, c(0.50, 0.995), na.rm = T), c("black", "green"))

colorList <- sapply(X = exptData$sampleId, FUN = function(x){return(meanColor)})

##################################################################################
## plot multiple profile plots for all the genes

multiProfiles_all <- multi_profile_plots(exptInfo = exptData,
                                         genesToPlot = geneInfo$gene,
                                         clusters = geneInfo,
                                         clusterColor = NULL,
                                         profileColors = colorList,
                                         expressionColor = NULL,
                                         matSource = matrixType,
                                         matBins = matrixDim,
                                         plotExpression = showExpressionHeatmap)

## gene length annotation
anGl <- gene_length_heatmap_annotation(bedFile = file_genes, genes = geneInfo$gene)


htlist_allGenes <- anGl$an + multiProfiles_all$heatmapList


## make sure that the order of genes in the heatmap list and in the dataframe is same
if(all(rownames(htlist_allGenes@ht_list[[exptData$profileName[1]]]@matrix) == geneInfo$gene)){
  ## set the row order by decreasing gene length
  rowOrd <- order(geneInfo$length, decreasing = TRUE)
}



wd <- 500 + (nrow(exptData) * 700) + (length(polII_ids) * 500 * showExpressionHeatmap)
title_all <- "test multiple profile plots"


# draw Heatmap and add the annotation name decoration
png(filename = "test_multi_profile.png", width=wd, height=3500, res = 270)

draw(htlist_allGenes,
     main_heatmap = exptData$profileName[1],
     # annotation_legend_list = list(profile1$legend),
     column_title = title_all,
     column_title_gp = gpar(fontsize = 14, fontface = "bold"),
     row_sub_title_side = "left",
     heatmap_legend_side = "bottom",
     gap = unit(c(5, multiProfiles_all$plotGaps, 5), "mm"),
     row_order = rowOrd,
     padding = unit(rep(0.5, times = 4), "cm")
)

add_annotation_titles(annotations = c("gene_length"), anTitle = anLables)

row_annotation_axis(an = "gene_length",
                    at = c(0, 2000, 4000),
                    labels = c("0kb", "2kb", ">4kb"),
                    slice = length(unique(geneInfo$cluster)))
dev.off()

##################################################################################
## profile plot for a subset of genes

